<script lang="ts">
  import {reduceShape} from '../../lib/curriculum';
  let batch=2,rows=3,cols=4,reduce='rows';
  $: input=[+batch,+rows,+cols]; $: axis={batch:0,rows:1,cols:2}[reduce] as number; $: axisLabel=reduce==='cols'?'columns':reduce; $: output=reduceShape(input,axis); $: reduced=input[axis]; $: cells=input.reduce((a,b)=>a*b,1); $: outputs=output.reduce((a,b)=>a*b,1);
</script>
<section class="lab" aria-labelledby="axis-title"><header><div><span>Axis lab</span><h3 id="axis-title">A reduction removes one named direction</h3></div><code>[batch, rows, columns]</code></header>
  <div class="story"><article><small>input</small><b>[{input.join(', ')}]</b><p>{cells} values</p></article><i>mean over <strong>{axisLabel}</strong><em>{reduced} values vote in each mean</em></i><article class="result"><small>output</small><b>[{output.join(', ')}]</b><p>{outputs} values</p></article></div>
  <div class="groups">{#each Array(outputs) as _,i}<div><small>output {i+1}</small>{#each Array(reduced) as _}<i></i>{/each}<b>→ one mean</b></div>{/each}</div>
  <div class="controls"><label>batch <b>{batch}</b><input type="range" min="1" max="4" step="1" bind:value={batch}/></label><label>rows <b>{rows}</b><input type="range" min="2" max="5" step="1" bind:value={rows}/></label><label>columns <b>{cols}</b><input type="range" min="2" max="6" step="1" bind:value={cols}/></label><label>reduce <select bind:value={reduce}><option value="batch">batch</option><option value="rows">rows</option><option value="cols">columns</option></select></label></div>
  <footer><code>x.mean(dim={axis})</code><span>`keepdim=True` would leave a size-1 placeholder instead of removing the axis.</span></footer></section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;padding:1rem}header span{font:800 .6rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}.story{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:1rem;padding:1rem;background:#121925;color:white}.story article{padding:.7rem;border:1px solid #394456;border-radius:8px;background:#1b2432}.story .result{border-color:var(--accent)}.story small{color:#8995a7;font:.53rem var(--font-mono)}.story b{display:block;font:.8rem var(--font-mono)}.story p{margin:.2rem 0 0;color:#929daf;font-size:.62rem}.story>i{text-align:center;font:normal .65rem var(--font-mono);color:#a5aebb}.story strong{color:var(--accent-light)}.story em{display:block;font:normal .52rem var(--font-mono)}.groups{display:flex;gap:.4rem;overflow:auto;padding:.8rem 1rem}.groups>div{min-width:78px;padding:.45rem;border:1px solid var(--border);border-radius:6px}.groups small,.groups b{display:block;font:.5rem var(--font-mono);color:var(--text-muted)}.groups i{display:inline-block;width:8px;height:8px;margin:3px 2px;border-radius:2px;background:var(--accent)}.controls{display:grid;grid-template-columns:repeat(4,1fr);gap:.8rem;padding:.8rem 1rem;border-top:1px solid var(--border)}.controls label{display:grid;grid-template-columns:1fr auto;color:var(--text-muted);font-size:.64rem}.controls input{grid-column:1/-1;accent-color:var(--accent)}.controls select{background:var(--bg);color:var(--text);border:1px solid var(--border)}footer{display:flex;justify-content:space-between;padding:.7rem 1rem;background:var(--accent-soft);font-size:.66rem}@media(max-width:620px){.story{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}footer{gap:.5rem;flex-direction:column}}
</style>
