<script lang="ts">
  import {conv2dGeometry} from '../../lib/curriculum';
  let size=32,inChannels=3,outChannels=16,kernel=3,stride=1,padding=1;
  $: geometry=conv2dGeometry(+size,+inChannels,+outChannels,+kernel,+stride,+padding); $: out=geometry.outputSize; $: params=geometry.parameters;
</script>
<section class="lab" aria-labelledby="cnnshape-title"><header><div><span>Geometry lab</span><h3 id="cnnshape-title">Track space, channels, and parameters separately</h3></div><strong>{params.toLocaleString()} trainable values</strong></header>
  <div class="pipeline"><article><small>input</small><b>[B, {inChannels}, {size}, {size}]</b><div class="stack in" style={`--layers:${Math.min(+inChannels,6)}`}></div></article><i>Conv2d<br/><code>{kernel}×{kernel}, s={stride}, p={padding}</code></i><article><small>feature map</small><b>[B, {outChannels}, {out}, {out}]</b><div class="stack out" style={`--layers:${Math.min(+outChannels,6)}`}></div></article></div>
  <div class="math"><code>floor(({size} + 2×{padding} − {kernel}) / {stride}) + 1 = {out}</code><code>{outChannels} × ({inChannels} × {kernel} × {kernel} weights + 1 bias) = {params}</code></div>
  <div class="controls"><label>input size <b>{size}</b><input type="range" min="16" max="64" step="8" bind:value={size}/></label><label>input channels <b>{inChannels}</b><input type="range" min="1" max="8" step="1" bind:value={inChannels}/></label><label>output channels <b>{outChannels}</b><input type="range" min="4" max="32" step="4" bind:value={outChannels}/></label><label>kernel <b>{kernel}</b><input type="range" min="1" max="7" step="2" bind:value={kernel}/></label><label>stride <b>{stride}</b><input type="range" min="1" max="3" step="1" bind:value={stride}/></label><label>padding <b>{padding}</b><input type="range" min="0" max="3" step="1" bind:value={padding}/></label></div>
  <footer>Batch size changes neither output geometry nor parameter count. More output channels create more learned filters; larger spatial maps create more filter applications.</footer></section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;padding:1rem}header span{font:800 .6rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}header strong{font:.72rem var(--font-mono);color:var(--accent)}.pipeline{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:2rem;padding:1.2rem;background:#121925;color:white}.pipeline article{text-align:center}.pipeline small{display:block;color:#8995a7;font:.53rem var(--font-mono)}.pipeline b{font:.75rem var(--font-mono)}.pipeline>i{font:normal .65rem var(--font-mono);color:var(--accent-light);text-align:center}.stack{width:120px;height:120px;margin:1rem auto 0;border:2px solid var(--accent);background:#253044;box-shadow:6px 6px #38465b,12px 12px #4b5b72}.stack.out{width:90px;height:90px;background:#3a2925}.math{display:flex;justify-content:space-between;gap:1rem;padding:.7rem 1rem;background:var(--accent-soft)}.math code{font-size:.63rem}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem;padding:.8rem 1rem}.controls label{display:grid;grid-template-columns:1fr auto;color:var(--text-muted);font-size:.63rem}.controls input{grid-column:1/-1;accent-color:var(--accent)}footer{padding:.7rem 1rem;border-top:1px solid var(--border);color:var(--text-muted);font-size:.67rem}@media(max-width:620px){.pipeline{grid-template-columns:1fr}.math{flex-direction:column}.controls{grid-template-columns:1fr 1fr}}
</style>
