<script lang="ts">
  import {bestValidationEpoch,generalizationLoss,type FitScenario} from '../../lib/curriculum';
  let scenario:FitScenario='overfit',epoch=24;
  const px=(e:number)=>42+e/40*476,py=(v:number)=>205-(v/1.5)*165;
  $: points=Array.from({length:41},(_,i)=>generalizationLoss(scenario,i));
  $: trainPath=points.map((v,i)=>`${i?'L':'M'} ${px(i)} ${py(v[0])}`).join(' '); $: valPath=points.map((v,i)=>`${i?'L':'M'} ${px(i)} ${py(v[1])}`).join(' ');
  $: current=points[+epoch]; $: best=bestValidationEpoch(scenario); $: diagnosis=scenario==='underfit'?'Both losses remain high: improve optimization, features, or capacity.':scenario==='learning'?'Both curves fall together: the fit is transferring.':'Training keeps improving after validation turns upward: memorization is taking over.';
</script>
  <section class="lab" aria-labelledby="gen-title"><header><div><span>Diagnosis lab</span><h3 id="gen-title">Two curves answer different questions</h3></div><div>{#each ['underfit','learning','overfit'] as s}<button class:active={scenario===s} onclick={()=>scenario=s as FitScenario}>{s}</button>{/each}</div></header>
  <div class="plot"><svg viewBox="0 0 560 245" role="img" aria-label={`${scenario} training and validation curves`}><line class="axis" x1="42" y1="205" x2="520" y2="205"/><path class="train" d={trainPath}/><path class="val" d={valPath}/><line class="cursor" x1={px(+epoch)} y1="30" x2={px(+epoch)} y2="205"/><circle class="train-dot" cx={px(+epoch)} cy={py(current[0])} r="5"/><circle class="val-dot" cx={px(+epoch)} cy={py(current[1])} r="5"/><text x="45" y="25">loss</text><text x="475" y="230">epoch</text></svg></div>
  <div class="readout"><label>inspect epoch <b>{epoch}</b><input type="range" min="0" max="40" step="1" bind:value={epoch}/></label><article><small>training loss</small><b>{current[0].toFixed(3)}</b></article><article><small>validation loss</small><b>{current[1].toFixed(3)}</b></article><article><small>best validation epoch</small><b>{best}</b></article></div>
  <footer><span><i></i> training answers “can the model fit?”</span><span><i></i> validation answers “does the fit transfer?”</span><strong>{diagnosis}</strong></footer></section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem}header span,.readout small{font:800 .6rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}header button{border:1px solid var(--border);background:var(--bg);color:var(--text);padding:.4rem;font-size:.63rem}header button.active{background:var(--accent);color:white}.plot{padding:.5rem 1rem;background:#121925}.plot svg{display:block;width:100%}.axis{stroke:#455064}.train,.val{fill:none;stroke-width:3}.train{stroke:var(--accent-light)}.val{stroke:#8ea6ca}.cursor{stroke:#657184;stroke-dasharray:4}.train-dot{fill:var(--accent)}.val-dot{fill:#8ea6ca}.plot text{fill:#8d99aa;font:10px var(--font-mono)}.readout{display:grid;grid-template-columns:1.4fr repeat(3,1fr)}.readout>*{padding:.8rem 1rem;border-right:1px solid var(--border)}.readout>*:last-child{border:0}.readout label{display:grid;grid-template-columns:1fr auto;color:var(--text-muted);font-size:.64rem}.readout input{grid-column:1/-1;accent-color:var(--accent)}.readout article b{font:.8rem var(--font-mono)}footer{display:flex;align-items:center;gap:1rem;flex-wrap:wrap;padding:.7rem 1rem;background:var(--accent-soft);font-size:.64rem}footer i{display:inline-block;width:16px;border-top:3px solid var(--accent);margin-right:.3rem}footer span+span i{border-color:#8ea6ca}footer strong{width:100%}@media(max-width:620px){header{align-items:flex-start;flex-direction:column}.readout{grid-template-columns:1fr 1fr}.readout label{grid-column:1/-1}}
</style>
