<script lang="ts">
  import {softmax2} from '../../lib/curriculum';
  let logit0=1.2,logit1=-.3,target=0,offset=0;
  $: a=(+logit0)+(+offset); $: b=(+logit1)+(+offset); $: probabilities=softmax2(a,b); $: p0=probabilities[0]; $: p1=probabilities[1]; $: loss=-Math.log(target===0?p0:p1);
  const width=(p:number)=>`${Math.max(2,p*100)}%`;
</script>
<section class="lab" aria-labelledby="logit-title">
  <header><div><span>Output lab</span><h3 id="logit-title">Scores become probabilities inside the loss</h3></div><div class="target"><span>correct class</span><button class:active={target===0} onclick={()=>target=0}>class 0</button><button class:active={target===1} onclick={()=>target=1}>class 1</button></div></header>
  <div class="classes"><article><small>class 0 logit</small><b>{a.toFixed(2)}</b><div><i style={`width:${width(p0)}`}></i></div><strong>{(p0*100).toFixed(1)}%</strong></article><article><small>class 1 logit</small><b>{b.toFixed(2)}</b><div><i style={`width:${width(p1)}`}></i></div><strong>{(p1*100).toFixed(1)}%</strong></article></div>
  <div class="readout"><article><small>prediction</small><b>class {p0>p1?0:1}</b></article><article><small>target probability</small><b>{(target===0?p0:p1).toFixed(3)}</b></article><article><small>cross-entropy</small><b>{loss.toFixed(3)}</b></article></div>
  <div class="controls"><label>class 0 raw logit <b>{(+logit0).toFixed(1)}</b><input type="range" min="-4" max="4" step=".1" bind:value={logit0}/></label><label>class 1 raw logit <b>{(+logit1).toFixed(1)}</b><input type="range" min="-4" max="4" step=".1" bind:value={logit1}/></label><label>add same offset to both <b>{(+offset).toFixed(1)}</b><input type="range" min="-5" max="5" step=".5" bind:value={offset}/></label></div>
  <footer><code>loss = −log(probability of the correct class)</code><span>Move the shared offset: logits change, but probabilities and loss do not. Only relative scores matter.</span></footer>
</section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem}header span,.readout small{font:800 .6rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}.target{display:flex;align-items:center;gap:.3rem}.target>span{font-size:.62rem;color:var(--text-muted)}.target button{border:1px solid var(--border);background:var(--bg);color:var(--text);padding:.4rem;font-size:.64rem}.target button.active{background:var(--accent);color:white}.classes{display:grid;grid-template-columns:1fr 1fr;gap:1rem;padding:1rem;background:#121925;color:white}.classes article{display:grid;grid-template-columns:1fr auto;gap:.3rem}.classes small{color:#8f9bad;font:.55rem var(--font-mono)}.classes b,.classes strong{font:.75rem var(--font-mono)}.classes div{grid-column:1/-1;height:18px;border:1px solid #3c4758;border-radius:99px;overflow:hidden}.classes i{display:block;height:100%;background:var(--accent);transition:.2s}.readout{display:grid;grid-template-columns:repeat(3,1fr)}.readout article{padding:.8rem 1rem;border-right:1px solid var(--border)}.readout article:last-child{border:0}.readout b{display:block;margin-top:.2rem;font:.8rem var(--font-mono)}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;padding:.8rem 1rem;border-top:1px solid var(--border)}.controls label{display:grid;grid-template-columns:1fr auto;color:var(--text-muted);font-size:.64rem}.controls input{grid-column:1/-1;accent-color:var(--accent)}footer{display:flex;justify-content:space-between;gap:1rem;padding:.7rem 1rem;background:var(--accent-soft);font-size:.66rem}footer span{color:var(--text-muted)}@media(max-width:620px){header{align-items:flex-start;flex-direction:column}.classes,.readout,.controls{grid-template-columns:1fr}.readout article{border-right:0;border-bottom:1px solid var(--border)}footer{flex-direction:column}}
</style>
