<script lang="ts">
  import {splitCounts} from '../../lib/curriculum';
  let total=100,trainPct=70,valPct=15,leaky=false;
  $: counts=splitCounts(+total,+trainPct,+valPct); $: train=counts.train; $: val=counts.validation; $: test=counts.test;
  const dots=40; $: trainDots=Math.round(dots*train/total); $: valDots=Math.round(dots*val/total);
</script>
<section class="lab" aria-labelledby="split-title"><header><div><span>Split lab</span><h3 id="split-title">Evaluation data observes; it does not teach</h3></div><div><button class:active={!leaky} onclick={()=>leaky=false}>Correct boundary</button><button class:active={leaky} onclick={()=>leaky=true}>Show leakage</button></div></header>
  <div class="dots">{#each Array(dots) as _,i}<i class:train={i<trainDots} class:val={i>=trainDots&&i<trainDots+valDots} class:test={i>=trainDots+valDots}></i>{/each}</div>
  <div class="splits"><article><span>train</span><b>{train}</b><p>fit parameters and preprocessing</p></article><article><span>validation</span><b>{val}</b><p>choose models and settings</p></article><article><span>test</span><b>{test}</b><p>final estimate, once</p></article></div>
  <div class="boundary" class:leaky><strong>{leaky?'Leak detected':'Clean information flow'}</strong><code>{leaky?'mean = all_examples.mean()':'mean = train_examples.mean()'}</code><p>{leaky?'Validation and test values influenced preprocessing used during training.':'Training statistics may transform every split, but evaluation values never fit those statistics.'}</p></div>
  <div class="controls"><label>examples <b>{total}</b><input type="range" min="50" max="200" step="10" bind:value={total}/></label><label>train % <b>{trainPct}</b><input type="range" min="60" max="75" step="5" bind:value={trainPct}/></label><label>validation % <b>{valPct}</b><input type="range" min="10" max="20" step="5" bind:value={valPct}/></label></div></section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem}header span,.splits span{font:800 .6rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}header button{border:1px solid var(--border);background:var(--bg);color:var(--text);padding:.4rem;font-size:.63rem}header button.active{background:var(--accent);color:white}.dots{display:flex;gap:5px;flex-wrap:wrap;padding:1rem;background:#121925}.dots i{width:12px;height:12px;border-radius:3px}.dots .train{background:var(--accent)}.dots .val{background:#e6b45d}.dots .test{background:#71809a}.splits{display:grid;grid-template-columns:repeat(3,1fr)}.splits article{padding:.8rem 1rem;border-right:1px solid var(--border)}.splits article:last-child{border:0}.splits b{display:block;font:1rem var(--font-mono)}.splits p{margin:.2rem 0;color:var(--text-muted);font-size:.64rem}.boundary{padding:.8rem 1rem;background:#e9f5e8;border-top:1px solid var(--border)}.boundary.leaky{background:#fde7e2}.boundary strong,.boundary code{margin-right:1rem;font-size:.7rem}.boundary p{margin:.3rem 0 0;color:var(--text-muted);font-size:.66rem}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;padding:.8rem 1rem}.controls label{display:grid;grid-template-columns:1fr auto;color:var(--text-muted);font-size:.64rem}.controls input{grid-column:1/-1;accent-color:var(--accent)}@media(max-width:620px){header{align-items:flex-start;flex-direction:column}.splits,.controls{grid-template-columns:1fr}.splits article{border-right:0;border-bottom:1px solid var(--border)}}
</style>
