<script lang="ts">
  import {examplesPerSecond,quantizeScalar,tensorStorageMB} from '../../lib/curriculum';
  type Stability = 'healthy' | 'exploding' | 'stalled';
  let stability:Stability='healthy',batch=64,stepMs=80,value=.63,quantStep=.25,qat=false,quantized=0,error=0;
  const curves:Record<Stability,number[]>={healthy:[1.15,.92,.76,.64,.54,.47,.41,.36,.32,.29,.27],exploding:[1.05,.88,.79,.95,.72,1.18,.84,1.55,1.12,1.9,2.35],stalled:[1.08,1.03,1.01,1,.99,.99,.98,.98,.98,.98,.98]};
  const diagnoses:Record<Stability,string>={healthy:'Finite gradients, a downward trend, and no widening train/validation gap.',exploding:'Spikes or non-finite values: inspect the learning rate, inputs, normalization, and gradient norm.',stalled:'Little movement: check data and labels, frozen parameters, gradient scale, and learning rate.'};
  const x=(i:number)=>36+i*45,y=(v:number)=>178-Math.min(v,2.5)/2.5*140;
  $: path=curves[stability].map((v,i)=>`${i?'L':'M'} ${x(i)} ${y(v)}`).join(' ');
  const elements=64*128*768,fp32=tensorStorageMB(elements,32),fp16=tensorStorageMB(elements,16);
  $: throughput=examplesPerSecond(+batch,+stepMs);
  $: ({quantized,error}=quantizeScalar(+value,+quantStep));
</script>
<section class="lab" aria-labelledby="constraints-title">
  <header><div><span>Systems lab</span><h3 id="constraints-title">Three budgets govern a training run</h3></div><p>numerical range · bytes · time</p></header>
  <article class="panel stability"><div class="copy"><small>1 · numerical health</small><h4>Would you trust this loss curve?</h4><div class="switch">{#each ['healthy','exploding','stalled'] as item}<button class:active={stability===item} onclick={()=>stability=item as Stability}>{item}</button>{/each}</div><p>{diagnoses[stability]}</p></div><svg viewBox="0 0 520 210" role="img" aria-label={`${stability} loss curve`}><line x1="36" y1="178" x2="492" y2="178"/><line x1="36" y1="25" x2="36" y2="178"/><path d={path}/><text x="40" y="20">loss</text><text x="447" y="200">steps</text></svg></article>
  <article class="panel memory"><div class="copy"><small>2 · memory and throughput</small><h4>Which number is actually limiting the run?</h4><p>For one saved activation tensor with shape <code>[64, 128, 768]</code>, eligible values take exactly half the storage at 16 bits. Standard automatic mixed precision usually keeps FP32 model parameters and optimizer state; it does not halve every byte in the run.</p></div><div class="budget"><div class="memory-bars"><div>FP32 <b>{fp32.toFixed(1)} MB</b><i style="--width:100%"></i></div><div>FP16/BF16 <b>{fp16.toFixed(1)} MB</b><i style="--width:50%"></i></div></div><div class="throughput"><label>batch <b>{batch}</b><input type="range" min="16" max="256" step="16" bind:value={batch}/></label><label>step time <b>{stepMs} ms</b><input type="range" min="20" max="240" step="10" bind:value={stepMs}/></label><strong>{throughput.toFixed(0)} examples / second</strong><small>Throughput = batch size ÷ step time. Measure it; precision alone cannot predict it.</small></div></div></article>
  <article class="panel quantization"><div class="copy"><small>3 · representational error</small><h4>When does rounding become part of learning?</h4><p>Post-training quantization changes inference after training. Quantization-aware training inserts simulated rounding in the forward pass so the model can adapt before export.</p><button class:active={qat} onclick={()=>qat=!qat}>{qat?'QAT: simulated during training':'PTQ: applied after training'}</button></div><div class="number-line"><div class="values"><span>original <b>{(+value).toFixed(2)}</b></span><span>stored level <b>{quantized.toFixed(2)}</b></span><span>error <b>{error>=0?'+':''}{error.toFixed(2)}</b></span></div><div class="track"><i class="original" style={`left:${(+value)*100}%`}></i><i class="rounded" style={`left:${quantized*100}%`}></i></div><label>value <input type="range" min="0" max="1" step=".01" bind:value={value}/></label><label>quantization step <b>{(+quantStep).toFixed(2)}</b><input type="range" min=".05" max=".5" step=".05" bind:value={quantStep}/></label><footer>{qat?'Forward: fake quantization exposes rounding error. Backward: a surrogate gradient keeps learning possible.':'Training remains full precision; rounding error appears only in the exported inference model.'}</footer></div></article>
</section>
<style>
  .lab{margin:2rem 0;border:1px solid var(--border);border-radius:16px;background:var(--surface);overflow:hidden;box-shadow:0 16px 45px var(--shadow)}header{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.1rem;border-bottom:1px solid var(--border)}header span,.copy small{font:800 .58rem var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}header h3{margin:.2rem 0}header p{margin:0;color:var(--text-muted);font:.61rem var(--font-mono)}.panel{display:grid;grid-template-columns:.9fr 1.3fr;border-bottom:1px solid var(--border)}.panel:last-child{border:0}.copy{padding:1rem}.copy h4{margin:.25rem 0 .6rem}.copy p{color:var(--text-muted);font-size:.66rem;line-height:1.55}.switch{display:flex}.copy button{border:1px solid var(--border);background:var(--bg);color:var(--text);padding:.4rem .55rem;font-size:.61rem}.copy button.active{background:var(--accent);border-color:var(--accent);color:white}.stability svg{width:100%;align-self:center;background:#121925}.stability line{stroke:#536075}.stability path{fill:none;stroke:#df7656;stroke-width:3}.stability text{fill:#9aa6b6;font:10px var(--font-mono)}.budget{padding:1rem;background:#121925;color:white}.memory-bars>div{display:grid;grid-template-columns:1fr auto;gap:.4rem;margin-bottom:.75rem;color:#aab4c3;font-size:.62rem}.memory-bars i{grid-column:1/-1;display:block;width:var(--width);height:16px;background:#71819a;border-radius:3px}.memory-bars>div+div i{background:#df7656}.throughput{display:grid;grid-template-columns:1fr 1fr;gap:.7rem;padding-top:.8rem;border-top:1px solid #303949}.throughput label{display:grid;grid-template-columns:1fr auto;color:#aab4c3;font-size:.61rem}.throughput input{grid-column:1/-1;accent-color:#df7656}.throughput strong,.throughput small{grid-column:1/-1}.throughput strong{font:.8rem var(--font-mono)}.throughput small{color:#8995a7;font-size:.58rem}.number-line{padding:1rem;background:#121925;color:white}.values{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem}.values span{padding:.55rem;border:1px solid #344054;color:#9aa6b6;font-size:.58rem}.values b{display:block;color:white;font:.75rem var(--font-mono)}.track{position:relative;height:4px;margin:2.2rem .6rem;background:#526076}.track i{position:absolute;top:50%;width:14px;height:14px;transform:translate(-50%,-50%);border-radius:50%}.track .original{background:#8ea6ca}.track .rounded{border:3px solid #df7656}.number-line label{display:grid;grid-template-columns:1fr auto;color:#aab4c3;font-size:.61rem}.number-line input{grid-column:1/-1;accent-color:#df7656}.number-line footer{margin-top:.8rem;padding:.6rem;background:#1d2735;color:#aab4c3;font-size:.61rem}@media(max-width:700px){header{align-items:flex-start;gap:.5rem;flex-direction:column}.panel{grid-template-columns:1fr}.stability svg{min-height:210px}.throughput{grid-template-columns:1fr}.values{grid-template-columns:1fr 1fr}.values span:last-child{grid-column:1/-1}}
</style>
